import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { StoreService } from '../core/store.service';
import { IconComponent } from '../shared/icon.component';
import { AuthService } from '../core/auth.service';
import { APP_CONFIG } from '../config/app-config';
import { RentReminder, Resident, Room } from '../core/models';

@Component({standalone:true,imports:[RouterLink,IconComponent,CommonModule],template:`
<div class="page-head"><div><p class="eyebrow">OPERATIONS OVERVIEW</p><h1>Good Morning, {{firstName}} 👋</h1><p>Everything that needs your attention, in one calm dashboard.</p></div><div class="date-card"><b>{{today}}</b><span>{{auth.tenant()?.name||config.property.name}} · {{auth.tenant()?.city||config.property.city}}</span></div></div>
<section class="command-ribbon" aria-label="Primary PG actions">
 <a class="command-card tenant" routerLink="/residents" [queryParams]="{add:'1'}"><span class="command-icon"><app-icon name="plus"/></span><span class="command-copy"><small>QUICK CHECK-IN</small><b>New Tenant</b><em>Daily or monthly · photo, ID proof & exact bed</em></span><span class="command-arrow">→</span></a>
 <a class="command-card vacancy" routerLink="/vacancy"><span class="command-icon"><app-icon name="bed"/></span><span class="command-copy"><small>LIVE AVAILABILITY</small><b>{{store.vacantBeds().length}} Vacant Beds</b><em>Block → Floor → Room → Bed</em></span><span class="command-arrow">→</span></a>
 <a class="command-card payment" routerLink="/payments"><span class="command-icon"><app-icon name="wallet"/></span><span class="command-copy"><small>RENT DESK</small><b>Rent Payment</b><em>Record payment with compulsory receipt</em></span><span class="command-arrow">→</span></a>
</section>
<div class="stats-grid">@for(s of stats;track s.label){<a class="stat-card" [routerLink]="s.link"><span class="stat-icon"><app-icon [name]="s.icon"/></span><div><strong>{{s.value}}</strong><span>{{s.label}}</span><small>{{s.meta}}</small></div></a>}</div>

@if(store.canAccess('payments')){
<section class="panel rent-command-card" role="button" tabindex="0" (click)="openRentAttention()" (keydown.enter)="openRentAttention()" aria-label="Open outstanding rent details">
 <div class="rent-command-copy"><div class="rent-command-icon">₹</div><div><p class="eyebrow">OUTSTANDING RENT</p><h2>Pending & Overdue Rent</h2><p>Block and floor-wise follow-up with resident, room, due date and direct contact actions.</p></div></div>
 <div class="rent-command-kpis"><article><span>Pending</span><b>{{unpaidRentItems.length}}</b><small>{{money(unpaidRentTotal)}} outstanding</small></article><article><span>Due today</span><b>{{dueTodayCount}}</b><small>Needs action today</small></article><article><span>Overdue</span><b>{{overdueAttentionCount}}</b><small>Past due / partial</small></article><article><span>Blocks</span><b>{{unpaidBlocks.length}}</b><small>With pending rent</small></article></div>
 <span class="rent-command-open">View rent attention <b>→</b></span>
</section>
}

<div class="dash-grid">
 <section class="panel occupancy"><div class="panel-head"><div><p class="eyebrow">LIVE CAPACITY</p><h2>Occupancy Overview</h2></div><a routerLink="/vacancy">View vacancy →</a></div><div class="occupancy-body"><div class="ring" [style.--occ]="occupancyPct"><div><b>{{occupancyPct}}%</b><span>Occupied</span></div></div><div class="legend"><p><i class="green"></i>Occupied <b>{{store.occupiedBeds()}}</b></p><p><i class="mint"></i>Available <b>{{store.vacantBeds().length}}</b></p><p><i class="amber"></i>Maintenance <b>{{maintenanceBeds}}</b></p><p><i class="slate"></i>Total beds <b>{{store.totalBeds()}}</b></p></div></div></section>
 <section class="panel"><div class="panel-head"><div><p class="eyebrow">PROPERTY</p><h2>Block-wise Summary</h2></div>@if(store.canAccess('property')){<a routerLink="/property">Open property →</a>}</div><div class="block-summary">@for(b of blockMetrics;track b.id){<article><span class="building-icon">{{b.id}}</span><div><b>{{b.name}}</b><strong>{{b.occupied}} / {{b.total}}</strong><small>{{b.vacant}} vacant · {{b.occupancy}}% occupied</small></div><div class="progress"><i [style.width.%]="b.occupancy"></i></div></article>}</div></section>
 <section class="panel quick"><div class="panel-head"><div><p class="eyebrow">SHORTCUTS</p><h2>Quick Actions</h2></div></div><div class="quick-grid"><a routerLink="/residents"><app-icon name="plus"/><span>Add Resident</span></a><a routerLink="/payments"><app-icon name="wallet"/><span>Record Payment</span></a><a routerLink="/vacancy"><app-icon name="bed"/><span>View Vacancy</span></a><a routerLink="/maintenance"><app-icon name="wrench"/><span>Maintenance</span></a></div></section>
</div>
<div class="insight-grid">
 <section class="panel"><div class="panel-head"><div><p class="eyebrow">ROOM MIX</p><h2>Sharing Distribution</h2></div><a routerLink="/amenities">Configure →</a></div><div class="mix-list">@for(item of sharingMix;track item.label){<div class="mix-row"><div><b>{{item.label}}</b><small>{{item.rooms}} rooms · {{item.beds}} beds</small></div><div class="mix-meter"><i [style.width.%]="item.pct"></i></div><strong>{{item.pct}}%</strong></div>}</div></section>
 <section class="panel"><div class="panel-head"><div><p class="eyebrow">ROOM TYPE</p><h2>AC vs Non-AC</h2></div><a routerLink="/amenities">Room setup →</a></div><div class="type-split"><article class="ac"><span>❄</span><div><b>{{acRooms}}</b><small>AC rooms</small></div></article><article><span>◌</span><div><b>{{normalRooms}}</b><small>Non-AC rooms</small></div></article></div></section>
 @if(store.role()==='owner'){
 <section class="panel rent-pulse"><div class="panel-head"><div><p class="eyebrow">OWNER FINANCE</p><h2>Rent Pulse · {{monthLabel}}</h2></div><a routerLink="/payments">Open payments →</a></div><div class="rent-numbers"><article><span>Expected</span><b>{{money(expectedRent)}}</b></article><article><span>Collected</span><b>{{money(collectedRent)}}</b></article><article><span>Pending</span><b>{{money(pendingRent)}}</b></article></div><div class="rent-health"><span class="good">{{paidCount}} Paid</span><span class="warn">{{partialCount}} Partial</span><span class="danger">{{overdueCount}} Overdue</span></div></section>
 }
</div>
<section class="panel room-strip"><div class="panel-head"><div><p class="eyebrow">ROOM MAP</p><h2>Live Room Snapshot</h2></div>@if(store.canAccess('property')){<a routerLink="/property">View all rooms →</a>}</div><div class="room-cards">@for(r of roomsPreview;track r.id){<article [class.has-vacancy]="vacancies(r)>0"><div class="room-top"><b>{{r.id}}</b><span>{{r.sharing}} Sharing</span></div><strong>{{r.beds.length-vacancies(r)}}/{{r.beds.length}}</strong><small>{{vacancies(r)>0 ? vacancies(r)+' bed available':'Fully occupied'}}</small><div class="bed-dots">@for(b of r.beds;track b.id){<i [class.free]="b.status==='vacant'"></i>}</div></article>}</div></section>
<div class="lower-grid">
 <section class="panel"><div class="panel-head"><h2>Today's Highlights</h2><a routerLink="/payments">View all</a></div><div class="activity-list"><div class="activity-item"><span>₹</span><div><b>{{store.dueTodayRentReminders().length}} rent dues today</b><small>{{store.overdueRentReminders().length}} overdue / partial · {{store.activeRentReminders().length}} active reminders</small></div></div><div class="activity-item"><span>＋</span><div><b>{{store.vacantBeds().length}} beds ready to assign</b><small>Use Vacancy to select exact block, floor and bed</small></div></div><div class="activity-item"><span>❄</span><div><b>{{acRooms}} AC rooms configured</b><small>{{normalRooms}} standard rooms available in inventory</small></div></div><div class="activity-item"><span>🏠</span><div><b>{{store.totalFloors()}} floors · {{store.rooms().length}} rooms</b><small>{{store.blocks().length}} active blocks in this property</small></div></div></div></section>
 <section class="panel"><div class="panel-head"><h2>Rent Attention</h2><button class="link-button" type="button" (click)="openRentAttention()">Open details →</button></div><div class="timeline">@for(r of attentionReminders;track r.residentId){<button class="timeline-item timeline-button" type="button" [class.alert]="r.status==='Overdue'" (click)="openResidentFromReminder(r)"><i></i><div><b>{{r.residentName}} · {{r.status}}</b><small>{{r.roomId}} · {{money(r.balance)}} balance · Due {{r.dueDate}}</small></div></button>}@empty{<div class="premium-empty"><span>✓</span><b>No urgent rent follow-up</b><small>Current reminder window is clear.</small></div>}</div></section>
</div>

@if(rentDeskOpen()){
<div class="modal-backdrop" (click)="closeRentAttention()">
 <section class="modal-shell rent-attention-modal" (click)="$event.stopPropagation()" aria-modal="true" role="dialog" aria-labelledby="rentAttentionTitle">
  <header class="modal-header"><div><p class="eyebrow">RENT FOLLOW-UP CENTER</p><h2 id="rentAttentionTitle">Pending & Overdue Rent</h2><p>Review unpaid residents by block and floor, then contact them directly.</p></div><button type="button" class="modal-x" (click)="closeRentAttention()" aria-label="Close">×</button></header>
  <div class="modal-body rent-attention-body">
   <div class="rent-modal-summary"><article><span>Total pending</span><b>{{money(unpaidRentTotal)}}</b><small>{{unpaidRentItems.length}} residents</small></article><article><span>Due today</span><b>{{dueTodayCount}}</b><small>Action today</small></article><article><span>Overdue / partial</span><b>{{overdueAttentionCount}}</b><small>Follow-up priority</small></article><article><span>Blocks</span><b>{{unpaidBlocks.length}}</b><small>With unpaid rent</small></article></div>
   @if(!unpaidRentItems.length){<div class="premium-empty rent-clear"><span>✓</span><h3>All current rent is clear</h3><p>No pending monthly rent records require follow-up.</p></div>}@else{
   <div class="rent-section-title"><div><span class="filter-tag">BLOCKS</span><h3>Select a block</h3><p>Each block shows pending residents and outstanding amount.</p></div></div>
   <div class="rent-block-grid">@for(group of unpaidBlocks;track group.blockId){<button type="button" class="rent-block-card" [class.active]="selectedRentBlock()===group.blockId" (click)="selectRentBlock(group.blockId)"><span class="rent-block-mark">{{group.blockId}}</span><div><b>{{group.blockName}}</b><small>{{group.floorCount}} floors · {{group.count}} residents</small></div><strong>{{money(group.total)}}</strong><em>View floors →</em></button>}</div>
   @if(selectedRentBlock()){
    <div class="rent-section-title rent-floor-title"><div><span class="filter-tag">FLOORS & ROOMS</span><h3>{{selectedBlockName()}}</h3><p>Residents are grouped by floor. Room number, due status and contact actions stay visible.</p></div><button type="button" class="secondary-btn compact" (click)="selectedRentBlock.set('');selectedRentResidentId.set('')">All Blocks</button></div>
    <div class="rent-floor-grid">@for(group of selectedBlockFloors();track group.floor){<article class="rent-floor-card"><div class="rent-floor-head"><div><span>{{floorName(group.floor)}}</span><b>{{group.count}} pending</b><small>{{group.roomCount}} rooms · {{money(group.total)}} outstanding</small></div><div class="rent-room-pills">@for(room of group.rooms;track room){<span>Room {{room}}</span>}</div></div><div class="rent-person-list">@for(item of group.items;track item.reminder.residentId){<div class="rent-person-row" [class.overdue]="item.reminder.status==='Overdue'"><button type="button" class="rent-person-main" (click)="selectedRentResidentId.set(item.reminder.residentId)"><span class="rent-person-avatar">{{initialsFor(item.resident?.name||item.reminder.residentName)}}</span><span class="rent-person-copy"><b>{{item.reminder.residentName}}</b><small>Room {{roomNumber(item.room)}} · {{item.room?.sharing||'—'}} Sharing · Due {{item.reminder.dueDate}}</small><em>{{item.reminder.status}} · {{money(item.reminder.balance)}} pending</em></span></button><div class="rent-contact-actions">@if(item.resident?.mobile){<a class="contact-btn call" [href]="telLink(item.resident!.mobile)" title="Call {{item.resident!.name}}"><span>☎</span><b>{{item.resident!.mobile}}</b></a><a class="contact-btn whatsapp" [href]="whatsappLink(item.resident!.mobile)" target="_blank" rel="noopener noreferrer" title="Open or check this number in WhatsApp"><span>WA</span><b>WhatsApp</b></a>}@else{<span class="contact-missing">No mobile number</span>}</div></div>}</div></article>}</div>
   }
   @if(selectedRentResident(); as selected){<section class="rent-resident-detail"><div class="rent-detail-head"><div class="rent-person-avatar large">{{initialsFor(selected.resident.name)}}</div><div><p class="eyebrow">RESIDENT RENT DETAILS</p><h3>{{selected.resident.name}}</h3><span>Room {{roomNumber(selected.room)}} · {{selected.room?.sharing||'—'}} Sharing · {{floorName(selected.room?.floor??0)}}</span></div><button class="modal-x" type="button" (click)="selectedRentResidentId.set('')">×</button></div><div class="rent-detail-grid"><article><span>Monthly rent</span><b>{{money(selected.resident.monthlyRent)}}</b></article><article><span>Paid this month</span><b>{{money(selected.reminder.paid)}}</b></article><article><span>Pending</span><b>{{money(selected.reminder.balance)}}</b></article><article><span>Status</span><b>{{selected.reminder.status}}</b></article><article><span>Due date</span><b>{{selected.reminder.dueDate}}</b></article><article><span>Joined</span><b>{{selected.resident.joined}}</b></article><article><span>Deposit</span><b>{{money(selected.resident.deposit)}}</b></article><article><span>Mobile</span><b>{{selected.resident.mobile||'—'}}</b></article></div><div class="rent-detail-actions">@if(selected.resident.mobile){<a class="primary-btn contact-link" [href]="telLink(selected.resident.mobile)">☎ Call Resident</a><a class="secondary-btn contact-link whatsapp-link" [href]="whatsappLink(selected.resident.mobile)" target="_blank" rel="noopener noreferrer">Open / Check WhatsApp</a>}<a class="secondary-btn contact-link" routerLink="/payments" (click)="closeRentAttention()">Open Rent Desk</a></div><p class="wa-privacy-note">WhatsApp account availability cannot be read silently from a browser. “Open / Check WhatsApp” opens this valid number in WhatsApp; WhatsApp itself confirms whether the number is registered.</p></section>}
   }
  </div>
  <footer class="modal-footer"><button type="button" class="secondary-btn" (click)="closeRentAttention()">Close</button><a class="primary-btn contact-link" routerLink="/payments" (click)="closeRentAttention()">Open Rent & Receipts</a></footer>
 </section>
</div>
}
`})
export class DashboardPage{
 today=new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date());
 monthLabel=new Intl.DateTimeFormat('en-IN',{month:'long',year:'numeric'}).format(new Date());
 readonly config=APP_CONFIG;
 rentDeskOpen=signal(false);selectedRentBlock=signal('');selectedRentResidentId=signal('');
 constructor(public store:StoreService,public auth:AuthService){}
 get firstName(){return (this.auth.user()?.name||'Owner').split(/\s+/)[0];}
 get occupancyPct(){return this.store.totalBeds()?Math.round((this.store.occupiedBeds()/this.store.totalBeds())*1000)/10:0;}
 get maintenanceBeds(){return this.store.rooms().reduce((n,r)=>n+r.beds.filter(b=>b.status==='maintenance'||b.status==='blocked').length,0);}
 get acRooms(){return this.store.rooms().filter(r=>r.ac).length;}
 get normalRooms(){return this.store.rooms().length-this.acRooms;}
 get expectedRent(){return this.store.activeResidents().reduce((n,r)=>n+Number(r.monthlyRent||0),0);}
 get collectedRent(){return this.store.rentReminders().reduce((n,r)=>n+r.paid,0);}
 get pendingRent(){return this.store.rentReminders().reduce((n,r)=>n+r.balance,0);}
 get paidCount(){return this.store.rentReminders().filter(r=>r.status==='Paid').length;}
 get partialCount(){return this.store.rentReminders().filter(r=>r.status==='Partial').length;}
 get overdueCount(){return this.store.rentReminders().filter(r=>r.status==='Overdue').length;}
 get attentionReminders(){return this.store.rentReminders().filter(r=>r.status==='Overdue'||r.status==='Partial'||r.status==='Due Today').slice(0,5);}
 get unpaidRentItems(){return this.store.rentReminders().filter(r=>r.status!=='Paid').map(reminder=>{const room=this.store.rooms().find(x=>x.id===reminder.roomId);const resident=this.store.activeResidents().find(x=>x.id===reminder.residentId);return{reminder,room,resident};});}
 get unpaidRentTotal(){return this.unpaidRentItems.reduce((n,x)=>n+x.reminder.balance,0);}
 get dueTodayCount(){return this.unpaidRentItems.filter(x=>x.reminder.status==='Due Today').length;}
 get overdueAttentionCount(){return this.unpaidRentItems.filter(x=>x.reminder.status==='Overdue'||x.reminder.status==='Partial').length;}
 get unpaidBlocks(){const groups=new Map<string,{blockId:string;blockName:string;count:number;total:number;floors:Set<number>}>();for(const item of this.unpaidRentItems){const blockId=item.room?.blockId||'Unknown';const block=this.store.blocks().find(b=>b.id===blockId);const current=groups.get(blockId)||{blockId,blockName:block?.name||blockId,count:0,total:0,floors:new Set<number>()};current.count++;current.total+=item.reminder.balance;if(item.room)current.floors.add(item.room.floor);groups.set(blockId,current);}return [...groups.values()].map(x=>({...x,floorCount:x.floors.size})).sort((a,b)=>a.blockName.localeCompare(b.blockName,undefined,{numeric:true}));}
 get blockMetrics(){return this.store.blocks().map(block=>{const rooms=this.store.rooms().filter(r=>r.blockId===block.id),beds=rooms.flatMap(r=>r.beds),total=beds.length,occupied=beds.filter(b=>b.status==='occupied').length,vacant=beds.filter(b=>b.status==='vacant').length;return{id:block.id,name:block.name,total,occupied,vacant,occupancy:total?Math.round(occupied/total*100):0};});}
 get sharingMix(){const total=Math.max(1,this.store.rooms().length);const counts=new Map<number,{rooms:number,beds:number}>();for(const r of this.store.rooms()){const cur=counts.get(r.sharing)||{rooms:0,beds:0};cur.rooms++;cur.beds+=r.beds.length;counts.set(r.sharing,cur);}return [...counts.entries()].sort((a,b)=>a[0]-b[0]).map(([sharing,v])=>({label:`${sharing} Sharing`,...v,pct:Math.round(v.rooms/total*100)}));}
 get stats(){const operational=[{label:'Active Residents',value:this.store.activeResidents().length,meta:'Current checked-in members',icon:'users',link:'/residents'},{label:'Total Beds',value:this.store.totalBeds(),meta:`Across ${this.store.blocks().length} blocks`,icon:'bed',link:'/property'},{label:'Available Beds',value:this.store.vacantBeds().length,meta:'Ready to assign',icon:'bed',link:'/vacancy'},{label:'Total Rooms',value:this.store.rooms().length,meta:`${this.store.totalFloors()} floors configured`,icon:'home',link:'/property'}];if(this.store.role()!=='owner')return operational;return [...operational,{label:'Rent Collected',value:this.money(this.collectedRent),meta:`${this.paidCount} paid this month`,icon:'wallet',link:'/payments'},{label:'Rent Pending',value:this.money(this.pendingRent),meta:`${this.overdueCount} overdue · ${this.partialCount} partial`,icon:'wallet',link:'/payments'}];}
 get roomsPreview(){return this.store.rooms().slice().sort((a,b)=>a.blockId.localeCompare(b.blockId)||a.floor-b.floor||a.number.localeCompare(b.number,undefined,{numeric:true})).slice(0,8);}
 vacancies(r:Room){return r.beds.filter(b=>b.status==='vacant').length;}
 money(value:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value||0);}
 openRentAttention(){this.rentDeskOpen.set(true);if(!this.selectedRentBlock()&&this.unpaidBlocks.length===1)this.selectedRentBlock.set(this.unpaidBlocks[0].blockId);}
 closeRentAttention(){this.rentDeskOpen.set(false);this.selectedRentResidentId.set('');}
 selectRentBlock(blockId:string){this.selectedRentBlock.set(blockId);this.selectedRentResidentId.set('');}
 selectedBlockName(){const id=this.selectedRentBlock();return this.store.blocks().find(b=>b.id===id)?.name||id;}
 selectedBlockFloors(){const blockId=this.selectedRentBlock(),map=new Map<number,any[]>();for(const item of this.unpaidRentItems){if((item.room?.blockId||'Unknown')!==blockId)continue;const floor=item.room?.floor??-1;const list=map.get(floor)||[];list.push(item);map.set(floor,list);}return [...map.entries()].sort((a,b)=>a[0]-b[0]).map(([floor,items])=>({floor,items,count:items.length,total:items.reduce((n,x)=>n+x.reminder.balance,0),rooms:[...new Set(items.map(x=>this.roomNumber(x.room)))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),roomCount:new Set(items.map(x=>x.room?.id||x.reminder.roomId)).size}));}
 selectedRentResident(){const id=this.selectedRentResidentId();if(!id)return null;const reminder=this.store.rentReminders().find(r=>r.residentId===id);const resident=this.store.activeResidents().find(r=>r.id===id);if(!reminder||!resident)return null;return{reminder,resident,room:this.store.rooms().find(r=>r.id===reminder.roomId)};}
 openResidentFromReminder(reminder:RentReminder){const room=this.store.rooms().find(r=>r.id===reminder.roomId);this.rentDeskOpen.set(true);this.selectedRentBlock.set(room?.blockId||'Unknown');this.selectedRentResidentId.set(reminder.residentId);}
 roomNumber(room:Room|undefined){return room?.number||room?.id||'—';}
 floorName(floor:number){if(floor<0)return'Unknown Floor';if(floor===0)return'Ground Floor';const n=floor%100;if(n>=11&&n<=13)return`${floor}th Floor`;switch(floor%10){case 1:return`${floor}st Floor`;case 2:return`${floor}nd Floor`;case 3:return`${floor}rd Floor`;default:return`${floor}th Floor`;}}
 initialsFor(name:string){return String(name||'R').trim().split(/\s+/).map(x=>x[0]||'').join('').slice(0,2).toUpperCase()||'R';}
 telLink(mobile:string){const n=String(mobile||'').replace(/\D/g,'').slice(-10);return`tel:+91${n}`;}
 whatsappLink(mobile:string){const n=String(mobile||'').replace(/\D/g,'').slice(-10);return`https://wa.me/91${n}`;}
}
