import { Component, OnDestroy, OnInit, computed, signal } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { StoreService } from '../core/store.service';
import { CloudDataService } from '../core/cloud-data.service';
import { FileStorageService } from '../core/file-storage.service';

type ModuleKey='food'|'staff'|'maintenance'|'assets'|'utilities'|'expenses'|'vendors'|'calendar'|'documents'|'notifications'|'activity';
interface Card{label:string;value:string;hint:string;tone?:string}
interface Row{[k:string]:any}
interface ModuleConfig{title:string;eyebrow:string;description:string;columns:{key:string;label:string}[];rows:Row[];primary:string;secondary?:string;ownerOnly?:boolean}

@Component({standalone:true,imports:[CommonModule,FormsModule],template:`
<div class="page-head">
 <div><p class="eyebrow">{{cfg().eyebrow}}</p><h1>{{cfg().title}}</h1><p>{{cfg().description}}</p></div>
 <div class="head-actions"><button class="secondary-btn" (click)="exportCsv()">Export CSV</button>@if(canCreate()){<button class="primary-btn" [disabled]="busy()" (click)="openForm()">+ {{cfg().primary}}</button>}</div>
</div>
@if(cfg().ownerOnly && store.role()!=='owner'){<div class="notice">This module requires Owner access.</div>}
<section class="stats-grid mini ops-stats">@for(c of liveCards();track c.label){<article class="stat-card"><div class="stat-icon">{{iconFor(c.label)}}</div><div><strong>{{c.value}}</strong><span>{{c.label}}</span><small>{{c.hint}}</small></div></article>}</section>
<section class="panel">
 <div class="panel-head"><div><p class="eyebrow">LIVE FIREBASE DATA</p><h2>{{cfg().title}} Overview</h2><p class="module-sync">{{cloud.configured?'Synced to this PG workspace in Firebase':'Local demo data'}}</p></div><div class="table-tools filter-tools"><span class="filter-tag">FILTERS</span><input [(ngModel)]="query" placeholder="Search this module..."><select [(ngModel)]="statusFilter"><option value="all">All statuses</option><option value="active">Active</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="completed">Completed</option><option value="read">Read</option></select></div></div>
 @if(message()){<div class="ops-message">✓ {{message()}}</div>}@if(error()){<div class="notice">{{error()}}</div>}
 @if(filteredRows().length){<div class="table-wrap"><table><thead><tr>@for(c of cfg().columns;track c.key){<th>{{c.label}}</th>}<th>Action</th></tr></thead><tbody>
 @for(row of filteredRows();track row['id']||$index){<tr>@for(c of cfg().columns;track c.key){<td><span [class]="c.key==='status'?'status '+statusClass(row[c.key]):''">{{row[c.key]}}</span></td>}<td><button class="link-btn" (click)="viewRow(row)">View</button></td></tr>}
 </tbody></table></div>}@else{<div class="premium-empty"><div class="empty-icon">✦</div><h3>No records yet</h3><p>{{cloud.configured?'This Firebase collection is empty for the current PG. Add the first real record below.':'No matching records.'}}</p>@if(cloud.configured&&exampleRow()){<div class="sample-record"><span>EXAMPLE PREVIEW · NOT SAVED</span><b>{{exampleSummary()}}</b><small>Use “+ {{cfg().primary}}” to add the first real Firebase record.</small></div>}@if(canCreate()){<button class="primary-btn" (click)="openForm()">+ {{cfg().primary}}</button>}</div>}
</section>
@if(selected()){
<div class="modal-backdrop" (click)="selected.set(null)"><section class="profile-modal modal-shell" (click)="$event.stopPropagation()">
 <div class="modal-header"><div><p class="eyebrow">DETAIL VIEW</p><h2>{{cfg().title}}</h2></div><button class="modal-x" (click)="selected.set(null)">×</button></div>
 <div class="modal-body"><div class="detail-grid">@for(c of cfg().columns;track c.key){<div><span>{{c.label}}</span><b>{{selected()![c.key]}}</b></div>}</div>@if(hasAttachment(selected())){<button class="secondary-btn secure-file-btn" (click)="openAttachment(selected()!)">Open encrypted attachment</button>}</div>
 <div class="modal-footer">@if(store.role()==='owner'&&canMutateSelected()){<button class="danger-outline" [disabled]="busy()" (click)="removeSelected()">Delete</button>}<span class="modal-spacer"></span><button class="secondary-btn" (click)="selected.set(null)">Close</button>@if(canMutateSelected()){<button class="secondary-btn" (click)="editSelected()">Edit</button><button class="primary-btn" [disabled]="busy()" (click)="markComplete()">{{key==='notifications'?'Mark Read':'Mark Completed'}}</button>}</div>
</section></div>}

@if(formOpen()){
<div class="modal-backdrop" (click)="closeForm()"><section class="form-modal modal-shell" (click)="$event.stopPropagation()">
 <div class="modal-header"><div><p class="eyebrow">{{editingId?'EDIT ENTRY':'NEW ENTRY'}}</p><h2>{{editingId?'Update '+cfg().title:cfg().primary}}</h2><p class="modal-subtitle">Saved directly inside this PG's Firebase tenant collection.</p></div><button class="modal-x" (click)="closeForm()">×</button></div>
 <div class="modal-body">
  @if(error()){<div class="notice modal-error-top">{{error()}}</div>}
  <div class="form-grid">
   @for(c of cfg().columns.slice(0,6);track c.key){
    <label>
     <span>{{c.label}}</span>
     @if(c.key==='status'){
      <select [(ngModel)]="draft[c.key]"><option>Active</option><option>Pending</option><option>Completed</option><option>Paid</option><option>Inactive</option></select>
     }@else{
      <input [(ngModel)]="draft[c.key]" [type]="inputType(c.key)" [placeholder]="'Enter '+c.label">
     }
    </label>
   }
  </div>
 @if(key!=='activity'){<label class="upload-card module-upload"><span class="upload-title"><i class="upload-orb">▣</i>{{key==='documents'?'Document file':'Optional attachment'}} @if(key==='documents'){<span class="required">Required</span>}</span><span class="upload-copy">Images, PDF, Word, Excel or text files are encrypted before upload to Cloudflare R2.</span><input type="file" accept="image/jpeg,image/png,image/webp,.pdf,.doc,.docx,.xls,.xlsx,.txt,.rtf" (change)="selectAttachment($event)">@if(attachmentFile){<div class="upload-preview">@if(attachmentPreview){<img [src]="attachmentPreview" alt="Attachment preview">}@else{<span class="document-preview">FILE</span>}<div><b>{{attachmentFile.name}}</b><span>{{fileSize(attachmentFile)}}</span></div></div>}@else if(currentFileName()){<div class="existing-file"><b>Current encrypted file</b><span>{{currentFileName()}}</span></div>}</label>}
 </div>
 <div class="modal-footer"><button class="secondary-btn" (click)="closeForm()">Cancel</button><button class="primary-btn" [disabled]="busy()" [attr.aria-busy]="busy()" (click)="saveDraft()">{{busy()?'Saving securely…':editingId?'Update Entry':'Save Securely'}}</button></div>
</section></div>}

@if(deleteConfirm()){
<div class="modal-backdrop" (click)="deleteConfirm.set(null)"><section class="premium-confirm-card" role="dialog" aria-modal="true" (click)="$event.stopPropagation()"><button class="modal-x" type="button" (click)="deleteConfirm.set(null)">×</button><div class="confirm-icon danger">!</div><p class="eyebrow">OWNER CONFIRMATION</p><h2>Delete this {{cfg().title}} record?</h2><p>This removes the Firebase record and, when present, its encrypted R2 attachment. This action cannot be undone.</p><div class="confirm-actions"><button class="secondary-btn" type="button" (click)="deleteConfirm.set(null)">Keep record</button><button class="danger-confirm-btn" type="button" [disabled]="busy()" (click)="confirmDelete()">{{busy()?'Deleting…':'Delete permanently'}}</button></div></section></div>}

`,styles:[`button:disabled{opacity:.45;cursor:not-allowed}.head-actions{display:flex;gap:8px}.table-tools{display:flex;gap:8px}.module-sync{font-size:9px!important;color:var(--muted);margin:2px 0 0!important}.detail-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin:18px 0}.detail-grid div{background:#f8fafc;border-radius:12px;padding:12px}.detail-grid span,.detail-grid b{display:block}.detail-grid span{font-size:10px;color:var(--muted);text-transform:uppercase;letter-spacing:.05em}.detail-grid b{margin-top:4px}.ops-message{margin:0 0 12px;padding:10px 12px;border-radius:12px;background:#ecfdf5;border:1px solid #c9f3df;color:#08775a;font-size:11px;font-weight:800}.premium-empty{text-align:center;padding:34px 18px;border:1px dashed #d7dbe6;border-radius:16px;background:linear-gradient(145deg,#fff,#fafbff)}.premium-empty>.empty-icon{width:42px;height:42px;display:grid;place-items:center;margin:0 auto 10px;border-radius:14px;background:linear-gradient(135deg,#6658f5,#14b8a6);color:white;font-size:18px}.premium-empty h3{margin:0 0 5px}.premium-empty p{margin:0 0 14px;color:var(--muted);font-size:11px}.sample-record{width:min(620px,100%);margin:0 auto 14px;padding:11px 13px;border:1px solid #e6e9f2;border-radius:13px;background:#fbfcff;text-align:left}.sample-record span,.sample-record b{display:block}.sample-record span{font-size:8px;font-weight:950;letter-spacing:.1em;color:#6d60d9}.sample-record b{margin-top:5px;font-size:11px;color:#334155;line-height:1.55}.sample-record small{display:block;margin-top:5px;color:#8a94a5;font-size:9px}.filter-tools{align-items:center}.filter-tag{font-size:8px;font-weight:950;letter-spacing:.12em;color:#5b50cf;background:#f0efff;border:1px solid #ddd9ff;border-radius:999px;padding:6px 8px;white-space:nowrap}.module-upload{margin-top:14px}.existing-file{margin-top:9px;padding:10px;border-radius:12px;background:#f4f7fb;display:grid;gap:3px}.existing-file span{font-size:9px;color:var(--muted)}.modal-spacer{flex:1}.secure-file-btn{margin-top:10px}.premium-confirm-card{position:relative;width:min(470px,calc(100vw - 24px));padding:26px;border-radius:24px;background:linear-gradient(155deg,#fff,#f8f9ff);box-shadow:0 28px 80px rgba(8,14,35,.28);border:1px solid #fff;text-align:center}.confirm-icon{display:grid;place-items:center;width:58px;height:58px;margin:0 auto 10px;border-radius:18px;background:linear-gradient(135deg,#fff0f0,#f0efff);font-size:24px;font-weight:950}.confirm-icon.danger{color:#b53e3e}.premium-confirm-card h2{margin:5px 0 7px;font-size:22px}.premium-confirm-card>p:not(.eyebrow){color:#6e7a8e;font-size:10px;line-height:1.55}.confirm-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:16px}@media(max-width:640px){.head-actions{margin-top:14px;display:grid;grid-template-columns:1fr 1fr}.table-tools{width:100%;display:grid}.detail-grid{grid-template-columns:1fr}}`]})
export class OperationsPage implements OnInit,OnDestroy{
 key:ModuleKey;query='';statusFilter='all';selected=signal<Row|null>(null);deleteConfirm=signal<Row|null>(null);formOpen=signal(false);draft:Row={};localRows=signal<Row[]>([]);message=signal('');error=signal('');busy=signal(false);attachmentFile?:File;attachmentPreview='';editingId='';editingRow:Row|null=null;private unsub?:()=>void;
 constructor(route:ActivatedRoute,public store:StoreService,public cloud:CloudDataService,private files:FileStorageService){this.key=(route.snapshot.data['module']||'activity') as ModuleKey;this.localRows.set(this.cloud.configured?[]:this.configs()[this.key].rows.slice(0,1));}
 async ngOnInit(){if(this.key==='activity')return;if(this.cloud.configured){try{this.localRows.set(await this.cloud.loadModuleRows(this.key));this.unsub=this.cloud.watchCollection<Row>(this.key,rows=>this.localRows.set(rows),e=>this.error.set(e?.message||'Realtime Firebase sync failed.'));}catch(e:any){this.error.set(e?.message||'Unable to load this Firebase module.');}}}
 ngOnDestroy(){this.unsub?.();this.clearAttachment();}
 cfg=computed(()=>({...this.configs()[this.key],rows:this.localRows()}));
 canCreate(){return this.key!=='activity'&&!(this.cfg().ownerOnly&&this.store.role()!=='owner');}
 liveCards=computed<Card[]>(()=>{if(this.key==='activity'){const rows=this.activityRows();return[{label:'Audit Records',value:String(rows.length),hint:'Immutable tenant actions'},{label:'Owner Actions',value:String(rows.filter(r=>String(r['actor']).startsWith('Owner')).length),hint:'Recorded actions'},{label:'Manager Actions',value:String(rows.filter(r=>String(r['actor']).startsWith('Manager')).length),hint:'Recorded actions'},{label:'Security',value:'Live',hint:'Name · role · time'}];}const rows=this.key==='notifications'?this.notificationRows():this.localRows(),status=(v:string)=>rows.filter(r=>String(r['status']||'').toLowerCase().includes(v)).length;return[{label:'Total Records',value:String(rows.length),hint:'Firebase records'},{label:'Active',value:String(status('active')),hint:'Currently active'},{label:'Pending',value:String(status('pending')),hint:'Needs attention'},{label:'Completed / Paid',value:String(status('completed')+status('paid')),hint:'Closed records'}];});
 filteredRows=computed(()=>{const q=this.query.toLowerCase().trim();const source=this.key==='notifications'?this.notificationRows():this.key==='activity'?this.activityRows():this.localRows();return source.filter(r=>{const text=Object.values(r).filter(v=>typeof v!=='object').join(' ').toLowerCase();const st=String(r['status']||'').toLowerCase();return(!q||text.includes(q))&&(this.statusFilter==='all'||st.includes(this.statusFilter));});});
 activityRows():Row[]{return this.store.auditLogs().map(a=>({id:a.id,time:new Date(a.createdAt).toLocaleString(),actor:`${a.actorRole==='owner'?'Owner':'Manager'} · ${a.actorName}`,action:a.action,module:a.module,status:'Completed'}));}
 notificationRows():Row[]{const rent=this.store.activeRentReminders().map(r=>({id:`rent-${r.residentId}`,time:r.status==='Due Today'?'Today':r.status==='Overdue'?'Overdue':r.status==='Partial'?'Partial payment':`Due ${r.dueDate}`,type:'Rent',message:`${r.residentName} · ${r.roomId} · ₹${r.balance.toLocaleString('en-IN')} ${r.status==='Partial'?'balance':'due'}`,priority:r.status==='Overdue'?'High':r.status==='Partial'?'High':r.status==='Due Today'?'High':'Normal',status:r.status==='Upcoming'?'Pending':r.status}));return[...rent,...this.localRows().filter(r=>r['type']!=='Rent')];}
 viewRow(row:Row){this.error.set('');this.selected.set(row);}
 hasAttachment(row:Row|null){return Boolean(row&&row['filePath']);}
 canMutateSelected(){const row=this.selected();return this.key!=='activity'&&!(this.key==='notifications'&&row?.['type']==='Rent');}
 currentFileName(){return String(this.editingRow?.['fileName']||'');}
 exampleRow(){return this.configs()[this.key]?.rows?.[0]||null;}
 exampleSummary(){const row=this.exampleRow();if(!row)return'';return this.cfg().columns.slice(0,3).map(c=>`${c.label}: ${row[c.key]??'—'}`).join(' · ');}
 openForm(){if(!this.canCreate())return;this.error.set('');this.editingId='';this.editingRow=null;this.draft={};this.clearAttachment();this.formOpen.set(true);}
 editSelected(){const row=this.selected();if(!row||this.key==='activity')return;this.selected.set(null);this.error.set('');this.editingId=String(row['id']||'');this.editingRow=row;this.draft={...row};this.clearAttachment();this.formOpen.set(true);}
 closeForm(){if(this.busy())return;this.formOpen.set(false);this.editingId='';this.editingRow=null;this.draft={};this.clearAttachment();}
 inputType(key:string){if(/(^|_)date$|joined/i.test(key))return'date';if(/amount|cost|salary|qty|quantity|count|reading|due$/i.test(key))return'text';if(/contact|mobile|phone/i.test(key))return'tel';return'text';}
 fileSize(f:File){return f.size<1024*1024?`${Math.max(1,Math.round(f.size/1024))} KB`:`${(f.size/1024/1024).toFixed(1)} MB`;}
 selectAttachment(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;this.clearAttachment();this.attachmentFile=f;this.attachmentPreview=f.type.startsWith('image/')?URL.createObjectURL(f):'';}
 clearAttachment(){if(this.attachmentPreview.startsWith('blob:'))URL.revokeObjectURL(this.attachmentPreview);this.attachmentPreview='';this.attachmentFile=undefined;}
 async saveDraft(){this.error.set('');const cols=this.cfg().columns,required=cols.slice(0,Math.min(2,cols.length));if(required.some(c=>!String(this.draft[c.key]||'').trim())){this.error.set('Please complete the first required fields.');return;}if(this.key==='documents'&&!this.attachmentFile&&!this.editingRow?.['filePath']){this.error.set('Select a document file before saving.');return;}this.busy.set(true);let uploadedPath='';try{const id=this.editingId||`${this.key.toUpperCase()}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,row:Row={id};cols.forEach(c=>row[c.key]=this.draft[c.key]??'—');if(cols.some(c=>c.key==='status')&&!row['status'])row['status']='Active';if(this.editingRow){for(const k of ['filePath','fileName','fileMime','fileProvider','fileEncryption'])if(this.editingRow[k])row[k]=this.editingRow[k];}const previousPath=String(this.editingRow?.['filePath']||'');if(this.attachmentFile){const stored=await this.files.upload(`${this.key}/${id}/attachments/${Date.now()}-${this.attachmentFile.name}`,this.attachmentFile);uploadedPath=stored.path;row['filePath']=stored.path;row['fileName']=stored.name;row['fileMime']=this.attachmentFile.type||'application/octet-stream';row['fileProvider']=stored.provider||'r2';row['fileEncryption']=stored.encryption||null;if(this.key==='documents'){row['name']=row['name']==='—'||!row['name']?stored.name:row['name'];row['uploaded']=new Date().toISOString().slice(0,10);}}
 await this.cloud.saveModuleRow(this.key,id,row as any);this.localRows.update(v=>[row,...v.filter(x=>String(x['id'])!==id)]);if(uploadedPath&&previousPath&&previousPath!==uploadedPath){void this.files.remove(previousPath).catch(()=>{});}await this.store.auditAction(this.editingId?'Entry updated':`${this.cfg().primary} created`,this.cfg().title,{module:this.key,id,attachment:Boolean(row['filePath'])});const wasEdit=Boolean(this.editingId);this.formOpen.set(false);this.editingId='';this.editingRow=null;this.draft={};this.clearAttachment();this.message.set(wasEdit?'Entry updated successfully.':`${this.cfg().primary} saved successfully.`);setTimeout(()=>this.message.set(''),2600);}catch(e:any){if(uploadedPath)void this.files.remove(uploadedPath).catch(()=>{});this.error.set(e?.message||'Unable to save this record.');}finally{this.busy.set(false);}}
 async markComplete(){const row=this.selected();if(!row||this.key==='activity')return;this.busy.set(true);this.error.set('');try{const notification=this.key==='notifications',updated:Row={...row,status:notification?'Read':'Completed'};await this.cloud.saveModuleRow(this.key,String(row['id']||''),updated as any);this.localRows.update(v=>v.map(x=>String(x['id']||'')===String(updated['id']||'')?updated:x));await this.store.auditAction(notification?'Notification marked read':'Entry marked completed',this.cfg().title,{module:this.key,id:row['id']});this.selected.set(null);this.message.set(notification?'Notification marked as read.':'Entry marked completed.');setTimeout(()=>this.message.set(''),2200);}catch(e:any){this.error.set(e?.message||'Unable to update record.');}finally{this.busy.set(false);}}
 removeSelected(){const row=this.selected();if(!row||this.store.role()!=='owner'||this.key==='activity')return;this.selected.set(null);this.deleteConfirm.set(row);}
 async confirmDelete(){const row=this.deleteConfirm();if(!row)return;this.busy.set(true);this.error.set('');try{await this.cloud.deleteModuleRow(this.key,String(row['id']||''));if(row['filePath'])void this.files.remove(String(row['filePath'])).catch(()=>{});this.localRows.update(v=>v.filter(x=>x['id']!==row['id']));await this.store.auditAction('Entry deleted',this.cfg().title,{module:this.key,id:row['id']});this.deleteConfirm.set(null);this.message.set('Entry deleted.');}catch(e:any){this.error.set(e?.message||'Unable to delete record.');}finally{this.busy.set(false);}}
 async openAttachment(row:Row){if(!row['filePath'])return;try{const url=await this.files.open(String(row['filePath']));window.open(url,'_blank','noopener,noreferrer');if(url.startsWith('blob:'))setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e:any){this.error.set(e?.message||'Unable to open encrypted attachment.');}}
 exportCsv(){const c=this.cfg().columns;const lines=[c.map(x=>x.label).join(','),...this.filteredRows().map(r=>c.map(x=>`"${String(r[x.key]??'').replaceAll('"','""')}"`).join(','))];const b=new Blob([lines.join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${this.key}-export.csv`;a.click();URL.revokeObjectURL(a.href);}
 iconFor(s:string){if(/rent|expense|salary|cost|purchase/i.test(s))return'₹';if(/staff|people|worker/i.test(s))return'👥';if(/issue|maintenance|repair/i.test(s))return'🔧';if(/food|meal|menu|stock/i.test(s))return'🍽';if(/document|receipt/i.test(s))return'📄';return'✦';}
 statusClass(v:any){const s=String(v).toLowerCase();return /pending|due|low|open|absent/.test(s)?'warn':/inactive|closed/.test(s)?'inactive':'';}
 configs():Record<ModuleKey,ModuleConfig>{return {
 food:{title:'Food & Kitchen',eyebrow:'MEALS • STOCK • COST',description:'Plan daily meals, kitchen stock and food expenses from one place.',primary:'Add Menu / Stock',columns:[{key:'meal',label:'Meal / Item'},{key:'details',label:'Menu / Stock'},{key:'qty',label:'Qty'},{key:'time',label:'Time'},{key:'status',label:'Status'}],rows:[{meal:'Breakfast',details:'Idly + Vada + Chutney',qty:'280 plates',time:'6:30–9:00 AM',status:'Active'}]},
 staff:{title:'Staff & Workers',eyebrow:'PEOPLE • ATTENDANCE • SALARY',description:'Manage workers, attendance, shifts, leave and payroll visibility.',primary:'Add Staff',columns:[{key:'name',label:'Staff Name'},{key:'role',label:'Role'},{key:'shift',label:'Shift'},{key:'phone',label:'Phone'},{key:'status',label:'Status'}],rows:[{name:'Ramesh',role:'Maintenance',shift:'9 AM–6 PM',phone:'9876500101',status:'Active'}]},
 maintenance:{title:'Maintenance',eyebrow:'ISSUES • ASSIGNMENTS • REPAIRS',description:'Track every room and common-area issue through closure.',primary:'New Issue',columns:[{key:'location',label:'Location'},{key:'issue',label:'Issue'},{key:'assigned',label:'Assigned To'},{key:'priority',label:'Priority'},{key:'status',label:'Status'}],rows:[{location:'A-302',issue:'Geyser not heating',assigned:'Ramesh',priority:'High',status:'Pending'}]},
 assets:{title:'Assets & Inventory',eyebrow:'ASSETS • CONDITION • SERVICE',description:'Know what is installed in every room, floor and common area.',primary:'Add Asset',columns:[{key:'asset',label:'Asset'},{key:'location',label:'Location'},{key:'assetId',label:'Asset ID'},{key:'condition',label:'Condition'},{key:'status',label:'Status'}],rows:[{asset:'Geyser 15L',location:'A-302',assetId:'GY-A302-01',condition:'Needs repair',status:'Pending'}]},
 utilities:{title:'Utilities',eyebrow:'POWER • WATER • GAS • INTERNET',description:'Track utility bills, meters, tanks, generators and service schedules.',primary:'Add Utility Record',columns:[{key:'utility',label:'Utility'},{key:'reference',label:'Meter / Reference'},{key:'period',label:'Period'},{key:'amount',label:'Amount / Reading'},{key:'status',label:'Status'}],rows:[{utility:'Electricity - Block A',reference:'EB-A-45821',period:'Sep 2026',amount:'₹22,400',status:'Paid'}]},
 expenses:{title:'Expenses',eyebrow:'OWNER FINANCE',description:'Operational expense ledger with categories, receipts and monthly visibility.',primary:'Add Expense',columns:[{key:'date',label:'Date'},{key:'category',label:'Category'},{key:'description',label:'Description'},{key:'amount',label:'Amount'},{key:'status',label:'Status'}],rows:[{date:'23 Sep',category:'Groceries',description:'Weekly vegetables',amount:'₹8,450',status:'Paid'}]},
 vendors:{title:'Vendors & Purchases',eyebrow:'SUPPLIERS • PURCHASES • DUES',description:'Manage recurring suppliers, purchases, bills and outstanding balances.',primary:'Add Vendor / Purchase',columns:[{key:'vendor',label:'Vendor'},{key:'category',label:'Category'},{key:'contact',label:'Contact'},{key:'due',label:'Outstanding'},{key:'status',label:'Status'}],rows:[{vendor:'Sri Lakshmi Foods',category:'Groceries',contact:'9876500211',due:'₹12,400',status:'Pending'}]},
 calendar:{title:'Operations Calendar',eyebrow:'DATES • DUES • SCHEDULES',description:'One operational calendar for rent, staff, maintenance and utilities.',primary:'Add Event',columns:[{key:'date',label:'Date'},{key:'event',label:'Event'},{key:'module',label:'Module'},{key:'owner',label:'Responsible'},{key:'status',label:'Status'}],rows:[{date:'25 Sep',event:'Rent due follow-up',module:'Payments',owner:'Manager',status:'Pending'}]},
 documents:{title:'Documents',eyebrow:'SECURE RECORDS',description:'Central view for resident proofs, receipts, staff records and property files.',primary:'Upload Document',columns:[{key:'name',label:'Document'},{key:'type',label:'Type'},{key:'linked',label:'Linked To'},{key:'uploaded',label:'Uploaded'},{key:'status',label:'Status'}],rows:[{name:'aadhaar-ravi.pdf',type:'Aadhaar',linked:'PG-00184 Ravi Kumar',uploaded:'12 Jan 2025',status:'Active'}]},
 notifications:{title:'Notifications',eyebrow:'ALERTS • REMINDERS',description:'Important operational alerts prioritized for immediate action.',primary:'Create Reminder',columns:[{key:'time',label:'Time'},{key:'type',label:'Type'},{key:'message',label:'Message'},{key:'priority',label:'Priority'},{key:'status',label:'Status'}],rows:[{time:'10 min ago',type:'Rent',message:'Ravi payment received ₹8,000',priority:'Normal',status:'Active'}]},
 activity:{title:'Activity Log',eyebrow:'SECURITY • ACCOUNTABILITY',description:'Immutable-style audit view of important Owner and Manager actions.',primary:'Add Note',columns:[{key:'time',label:'Time'},{key:'actor',label:'Actor'},{key:'action',label:'Action'},{key:'module',label:'Module'},{key:'status',label:'Status'}],rows:[{time:'10:42 PM',actor:'Manager',action:'Recorded Ravi payment ₹8,000',module:'Payments',status:'Completed'}]},
 }}
}
