import { Component, computed, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { StoreService } from '../core/store.service';
import { FileStorageService } from '../core/file-storage.service';
import { Payment } from '../core/models';
@Component({standalone:true,imports:[FormsModule],template:`
<div class="page-head"><div><p class="eyebrow">FINANCE</p><h1>Rent & Payments</h1><p>Rent, advances, deposits and receipt-backed transactions.</p></div><button class="primary-btn" (click)="open.set(true)">+ Record Payment</button></div>
@if(store.role()==='owner'){<div class="stats-grid mini"><article class="stat-card"><div><strong>₹{{expected().toLocaleString('en-IN')}}</strong><span>Expected rent</span><small>Owner-only total</small></div></article><article class="stat-card"><div><strong>₹{{collected().toLocaleString('en-IN')}}</strong><span>Recorded rent</span><small>Owner-only total</small></div></article><article class="stat-card"><div><strong>₹{{pending().toLocaleString('en-IN')}}</strong><span>Pending</span><small>Owner-only total</small></div></article><article class="stat-card"><div><strong>₹{{deposits().toLocaleString('en-IN')}}</strong><span>Deposits Held</span><small>Owner-only total</small></div></article></div>}@else{<div class="stats-grid mini manager-payment-stats"><article class="stat-card"><div><strong>{{store.activeResidents().length}}</strong><span>Active residents</span><small>Payment operations enabled</small></div></article><article class="stat-card"><div><strong>{{store.payments().length}}</strong><span>Receipts recorded</span><small>Transaction amounts stay in the ledger</small></div></article><article class="stat-card"><div><strong>{{partialCount}}</strong><span>Partial payments</span><small>Follow-up required</small></div></article><article class="stat-card"><div><strong>Required</strong><span>Receipt proof</span><small>Every payment must include proof</small></div></article></div>}

<section class="panel daily-stay-panel"> <div class="panel-head"><div><p class="eyebrow">DAILY STAY BILLING</p><h2>Daily Guests</h2></div><span class="reminder-count">{{store.dailyGuests().length}} active</span></div><div class="reminder-grid">@for(a of store.dailyStayAccounts();track a.resident.id){<article class="reminder-card daily-card"><div><b>{{a.resident.name}}</b><small>{{a.resident.id}} · {{a.roomId}} · Since {{a.from}}</small></div><span class="status">Daily</span><div class="rent-money"><strong>₹{{a.balance.toLocaleString('en-IN')}}</strong><small>{{a.days}} day{{a.days===1?'':'s'}} × ₹{{(a.resident.dailyRate||0).toLocaleString('en-IN')}} · ₹{{a.paid.toLocaleString('en-IN')}} paid</small></div>@if(a.balance>0){<button class="link-btn" (click)="payReminder(a.resident.id,a.balance)">Record daily payment →</button>}@else{<span class="paid-note">✓ Current running bill covered</span>}</article>}@empty{<div class="empty-cell">No active daily-stay guests.</div>}</div></section>
<section class="panel rent-reminder-panel">
 <div class="panel-head"><div><p class="eyebrow">MONTHLY RENT CYCLE</p><h2>Monthly Rent Reminders</h2></div><span class="reminder-count">{{store.activeRentReminders().length}} active</span></div>
 <div class="reminder-grid">@for(r of store.rentReminders();track r.residentId){<article class="reminder-card" [class.paid]="r.status==='Paid'" [class.overdue]="r.status==='Overdue'||r.status==='Partial'" [class.today]="r.status==='Due Today'"><div><b>{{r.residentName}}</b><small>{{r.residentId}} · {{r.roomId}} · Due {{store.ordinal(r.dueDay)}}</small></div><span class="status">{{r.status}}</span><div class="rent-money"><strong>₹{{r.balance.toLocaleString('en-IN')}}</strong><small>{{r.status==='Paid'?'No reminder until next month':(r.paid?'₹'+r.paid.toLocaleString('en-IN')+' paid · balance pending':'Monthly rent ₹'+r.monthlyRent.toLocaleString('en-IN'))}}</small></div>@if(r.status!=='Paid'){<button class="link-btn" (click)="payReminder(r.residentId,r.balance)">Record payment →</button>}@else{<span class="paid-note">✓ Reminder stopped for this month</span>}</article>}</div>
</section>
<section class="panel table-wrap"><table><thead><tr><th>Resident</th><th>Room</th><th>Type</th><th>Amount</th><th>Mode</th><th>Date</th><th>Receipt</th><th>Status</th></tr></thead><tbody>@for(p of store.payments();track p.id){<tr><td><b>{{p.residentName}}</b><small>{{p.residentId}}</small></td><td>{{p.roomId}}</td><td>{{p.type}}</td><td>₹{{p.amount.toLocaleString('en-IN')}}</td><td>{{p.mode}}</td><td>{{p.date}}</td><td>@if(p.receipt.path){<button class="link-btn doc-ok" (click)="openReceipt(p.receipt.path,p.receipt.url||'')">✓ {{p.receipt.name}}</button>}@else{<span class="doc-ok">✓ {{p.receipt.name}}</span>}</td><td><span class="status" [class.inactive]="p.status==='Partial'">{{p.status}}</span></td></tr>}@empty{<tr><td colspan="8" class="empty-cell">No payments recorded yet.</td></tr>}</tbody></table></section>
@if(open()){
<div class="modal-backdrop" (click)="closeModal()"><article class="form-modal modal-shell" (click)="$event.stopPropagation()">
 <div class="modal-header"><div><p class="eyebrow">SECURE TRANSACTION</p><h2>Record Payment</h2><p class="modal-subtitle">Receipt or payment proof is mandatory for every transaction.</p></div><button class="modal-x" (click)="closeModal()">×</button></div>
 <div class="modal-body">@if(error()){<div class="notice modal-error-top">{{error()}}</div>}<div class="form-grid"><label>Resident<select [(ngModel)]="draft.residentId"><option value="">Select resident</option>@for(r of store.activeResidents();track r.id){<option [value]="r.id">{{r.id}} · {{r.name}} · {{activeRoom(r)}}</option>}</select></label><label>Payment type<select [(ngModel)]="draft.type"><option>Rent</option><option>Advance</option><option>Deposit</option><option>Other</option></select></label><label>Amount<input type="number" [(ngModel)]="draft.amount"></label><label>Payment mode<select [(ngModel)]="draft.mode"><option>UPI</option><option>Cash</option><option>Bank Transfer</option><option>Cheque</option></select></label><label class="wide upload-card"><span class="upload-title"><i class="upload-orb">₹</i>Receipt / payment proof <span class="required">Required</span></span><span class="upload-copy">Upload screenshot, receipt image or PDF. Preview it before the encrypted R2 save.</span><input type="file" accept="image/jpeg,image/png,image/webp,.pdf,application/pdf" (change)="file($event)">@if(receiptFile){<div class="upload-preview">@if(receiptPreview){<img [src]="receiptPreview" alt="Receipt preview">}@else{<span class="document-preview">PDF</span>}<div><b>{{receiptFile.name}}</b><span>{{fileSize(receiptFile)}}</span></div></div>}</label><label class="wide">Reference / note<input [(ngModel)]="draft.note" placeholder="UPI ref, bank ref or cash note"></label></div></div>
 <div class="modal-footer"><button class="secondary-btn" (click)="closeModal()">Cancel</button><button class="primary-btn" [disabled]="busy()" [attr.aria-busy]="busy()" (click)="save()">{{busy()?'Uploading & saving…':'Save Payment & Receipt'}}</button></div>
</article></div>}

`,styles:[`.daily-stay-panel,.rent-reminder-panel{margin-bottom:16px}.daily-card{border-color:#a7f3d0;background:linear-gradient(145deg,#fff,#f0fdf8)}.reminder-count{font-weight:800;color:#4f46e5;background:#eef2ff;padding:7px 11px;border-radius:999px}.reminder-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,250px),1fr));gap:12px}.reminder-card{border:1px solid var(--line);border-radius:18px;padding:15px;background:linear-gradient(145deg,#fff,#f8fafc);display:grid;gap:10px}.reminder-card.overdue{border-color:#fecaca;background:linear-gradient(145deg,#fff,#fff7f7)}.reminder-card.today{border-color:#fde68a;background:linear-gradient(145deg,#fff,#fffbeb)}.reminder-card.paid{border-color:#bbf7d0;background:linear-gradient(145deg,#fff,#f0fdf4)}.reminder-card b,.reminder-card small{display:block}.reminder-card small{color:var(--muted);margin-top:3px}.rent-money strong{font-size:20px}.paid-note{font-size:11px;font-weight:800;color:#15803d}.required{font-size:10px;color:#b42318;background:#fff1f0;padding:2px 6px;border-radius:999px}.empty-cell{text-align:center;color:var(--muted);padding:30px}`]})
export class PaymentsPage{
 open=signal(false);error=signal('');busy=signal(false);receiptFile?:File;receiptPreview='';draft:{residentId:string;type:Payment['type'];amount:number;mode:string;note:string}={residentId:'',type:'Rent',amount:0,mode:'UPI',note:''};
 constructor(public store:StoreService,private files:FileStorageService,route:ActivatedRoute){route.queryParamMap.subscribe(p=>{const resident=p.get('resident');if(resident&&this.store.activeResidents().some(r=>r.id===resident)){this.draft.residentId=resident;this.error.set('');this.open.set(true);}});}
 payReminder(residentId:string,balance:number){this.draft={residentId,type:'Rent',amount:balance,mode:'UPI',note:''};this.error.set('');this.open.set(true)}
 expected=computed(()=>this.store.monthlyResidents().reduce((n,r)=>n+r.monthlyRent,0)+this.store.dailyStayAccounts().reduce((n,a)=>n+a.expected,0));
 collected=computed(()=>this.store.payments().filter(p=>p.type==='Rent').reduce((n,p)=>n+p.amount,0));
 pending=computed(()=>Math.max(0,this.expected()-this.collected()));
 deposits=computed(()=>this.store.activeResidents().reduce((n,r)=>n+r.deposit,0));
 get partialCount(){return this.store.payments().filter(p=>p.status==='Partial').length}
 activeRoom(r:any){return r.stays.find((s:any)=>s.active)?.roomId||'—'}
 async openReceipt(path:string,url=''){try{const target=await this.files.open(path,url);window.open(target,'_blank','noopener,noreferrer');if(target.startsWith('blob:'))setTimeout(()=>URL.revokeObjectURL(target),60000);}catch(e:any){this.error.set(e?.message||'Unable to open secure receipt.')}}
 fileSize(f:File){return f.size<1024*1024?`${Math.max(1,Math.round(f.size/1024))} KB`:`${(f.size/1024/1024).toFixed(1)} MB`;}
 closeModal(){if(this.busy())return;this.open.set(false);if(this.receiptPreview.startsWith('blob:'))URL.revokeObjectURL(this.receiptPreview);this.receiptPreview='';this.receiptFile=undefined;}
 file(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;if(this.receiptPreview.startsWith('blob:'))URL.revokeObjectURL(this.receiptPreview);this.receiptFile=f;this.receiptPreview=f.type.startsWith('image/')?URL.createObjectURL(f):'';}
 async save(){this.error.set('');if(!this.draft.residentId||!this.draft.amount||!this.receiptFile){this.error.set('Resident, payment amount and receipt/proof upload are compulsory.');return}this.busy.set(true);try{await this.store.recordPayment({...this.draft,receiptFile:this.receiptFile});this.open.set(false);this.draft={residentId:'',type:'Rent',amount:0,mode:'UPI',note:''};if(this.receiptPreview.startsWith('blob:'))URL.revokeObjectURL(this.receiptPreview);this.receiptPreview='';this.receiptFile=undefined}catch(e:any){this.error.set(e?.message||'Unable to save payment.')}finally{this.busy.set(false)}}
}
