import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { StoreService } from '../core/store.service';
import { AuthService } from '../core/auth.service';
import { FileStorageService } from '../core/file-storage.service';
import { PagePermission } from '../core/models';
import { APP_CONFIG } from '../config/app-config';
import { environment } from '../../environments/environment';
import { CloudDataService } from '../core/cloud-data.service';
@Component({standalone:true,imports:[FormsModule],template:`
<div class="page-head"><div><p class="eyebrow">OWNER CONTROL</p><h1>Settings & Branding</h1><p>Each PG has its own name, city, encrypted logo, users and operational database.</p></div><button class="secondary-btn" (click)="store.resetManagerAccess()">Reset Recommended Access</button></div>
<section class="panel settings-hero"><div><p class="eyebrow">CURRENT PG</p><h2>{{auth.tenant()?.name}}</h2><p>Tenant ID: {{auth.user()?.tenantId}} · All operational collections are isolated below this tenant.</p></div><div class="role-cards"><article><span>OWNER</span><b>Full Tenant Access</b><small>Users · Finance · Settings · Security</small></article><article><span>MANAGER</span><b>Custom Access</b><small>{{store.managerAccess().length}} default pages</small></article></div></section>
<section class="panel"><div class="panel-head"><div><p class="eyebrow">PG IDENTITY</p><h2>Name, City & Logo</h2><p>Branding appears in the sidebar, mobile header and footer only for this PG.</p></div><span class="secure-pill">Tenant Specific</span></div><div class="form-grid"><label>PG name<input [(ngModel)]="brand.name"></label><label>Short name<input [(ngModel)]="brand.shortName"></label><label>City<input [(ngModel)]="brand.city"></label><label class="upload-card"> <span class="upload-title"><i class="upload-orb">P</i>PG Logo</span><span class="upload-copy">PNG, JPG or WebP. Preview the logo here; the saved file is encrypted in R2.</span><input type="file" accept="image/jpeg,image/png,image/webp" (change)="selectLogo($event)">@if(logoFile){<div class="upload-preview logo-preview"><img [src]="logoPreview" alt="PG logo preview"><div><b>{{logoFile.name}}</b><span>{{fileSize(logoFile)}}</span></div></div>}</label></div>@if(brandMessage()){<div class="ops-message">{{brandMessage()}}</div>}@if(brandError()){<div class="notice">{{brandError()}}</div>}<div style="margin-top:12px"><button class="primary-btn" [disabled]="brandSaving()" (click)="saveBrand()">{{brandSaving()?'Saving…':'Save PG Branding'}}</button></div></section>
<section class="panel access-panel"><div class="panel-head"><div><p class="eyebrow">MANAGER ACCESS</p><h2>Recommended Manager Permission Template</h2></div><span class="secure-pill">New Manager Template</span></div><div class="permission-grid">@for(p of permissions;track p.key){<label class="permission-card" [class.enabled]="store.managerAccess().includes(p.key)"><span class="permission-switch"><input type="checkbox" [checked]="store.managerAccess().includes(p.key)" (change)="store.setManagerPageAccess(p.key,$any($event.target).checked)"><i></i></span><div><b>{{p.label}}</b><small>{{p.desc}}</small></div><em>{{store.managerAccess().includes(p.key)?'Visible':'Hidden'}}</em></label>}</div></section>
<section class="panel readiness-panel"><div class="panel-head"><div><p class="eyebrow">PRODUCTION READINESS</p><h2>Provider & Data Health</h2></div><button class="secondary-btn" (click)="downloadBackup()">Download This PG Backup</button></div><div class="lock-grid"><article><b>Data Provider</b><small>{{dataProvider}} · tenant isolated</small></article><article><b>File Provider</b><small>{{fileProvider}} · AES-GCM encrypted</small></article><article><b>Firebase Config</b><small>{{firebaseReady?'Configured':'Not configured'}}</small></article><article><b>R2 Encrypted Vault</b><small>{{r2Status()}}</small></article><article><b>Push Notifications</b><small>{{pushReady?'VAPID configured':'VAPID key required'}}</small></article><article><b>Firebase App Check</b><small>{{appCheckReady?'Configured':'Recommended before public launch'}}</small></article><article><b>Data Integrity</b><small>{{integrityCount===0?'Healthy':integrityCount+' issue(s)'}}</small></article></div></section>
<section class="panel security-clarity"><div class="panel-head"><div><p class="eyebrow">DATA PROTECTION</p><h2>What is encrypted and where</h2><p>Clear production status without hiding security limitations.</p></div><span class="secure-pill">Owner Visibility</span></div><div class="security-facts"><article><span>FILES</span><b>AES-GCM before R2 storage</b><small>Resident photos, ID proofs, receipts, logos and uploaded documents are encrypted before the encrypted object is stored in R2.</small></article><article><span>FIRESTORE DATA</span><b>TLS + Firebase encryption at rest</b><small>Names, email, mobile, room, rent and operational fields are structured Firestore data. They are not zero-knowledge field-encrypted inside this app because search, permissions and workflows need them.</small></article><article><span>FIREBASE STORAGE</span><b>Disabled</b><small>Binary uploads are intentionally blocked by Firebase Storage rules. Files use the R2 vault only.</small></article><article><span>DEVICE LOCK</span><b>PBKDF2-protected PIN</b><small>The local app-lock PIN is derived with a random salt and rate-limited. Firebase Authentication remains the real account security boundary.</small></article></div></section>
`})
export class SettingsPage{
 dataProvider=APP_CONFIG.dataProvider;fileProvider=APP_CONFIG.fileProvider;firebaseReady=Boolean(environment.firebase.apiKey&&environment.firebase.projectId);pushReady=Boolean(environment.firebase.vapidKey);appCheckReady=Boolean(environment.appCheckSiteKey);r2Status=signal('Checking…');logoFile:File|null=null;logoPreview='';brandSaving=signal(false);brandMessage=signal('');brandError=signal('');brand={name:'',shortName:'',city:''};
 constructor(public store:StoreService,public auth:AuthService,private files:FileStorageService,private cloud:CloudDataService){const t=auth.tenant();this.brand={name:t?.name||'',shortName:t?.shortName||'',city:t?.city||''};void this.checkR2();}
 get integrityCount(){return this.store.integrityIssues().length;}
 fileSize(f:File){return f.size<1024*1024?`${Math.max(1,Math.round(f.size/1024))} KB`:`${(f.size/1024/1024).toFixed(1)} MB`;}
 selectLogo(e:Event){const f=(e.target as HTMLInputElement).files?.[0]||null;if(this.logoPreview.startsWith('blob:'))URL.revokeObjectURL(this.logoPreview);this.logoFile=f;this.logoPreview=f?URL.createObjectURL(f):'';}
 async saveBrand(){this.brandError.set('');if(!this.brand.name.trim()||!this.brand.shortName.trim()){this.brandError.set('PG name and short name are required.');return;}this.brandSaving.set(true);try{let logo=this.auth.tenant()?.logo;if(this.logoFile){const stored=await this.files.upload(`branding/logo/${Date.now()}-${this.logoFile.name}`,this.logoFile);logo={type:'PG Logo',...stored,uploadedAt:new Date().toISOString().slice(0,10)};}await this.auth.updateTenantBranding({name:this.brand.name.trim(),shortName:this.brand.shortName.trim(),city:this.brand.city.trim(),logo});await this.store.auditAction('PG branding updated','Settings',{name:this.brand.name.trim(),city:this.brand.city.trim(),logoUpdated:Boolean(this.logoFile)});this.logoFile=null;if(this.logoPreview.startsWith('blob:'))URL.revokeObjectURL(this.logoPreview);this.logoPreview='';this.brandMessage.set('PG branding updated.');}catch(e:any){this.brandError.set(e?.message||'Unable to update branding.');}finally{this.brandSaving.set(false);}}
 async checkR2(){try{const h:any=await this.files.health();this.r2Status.set(h?.ok?'Connected · AES-GCM':'Unavailable');}catch{this.r2Status.set('Unavailable');}}
 async downloadBackup(){const cloudData=this.cloud.configured?await this.cloud.exportTenantSnapshot():{};const data=JSON.stringify({...this.store.exportBackup(),firebaseCollections:cloudData,tenant:{id:this.auth.user()?.tenantId,name:this.auth.tenant()?.name}},null,2);const blob=new Blob([data],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${this.auth.user()?.tenantId||'pg'}-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);}
 permissions:{key:PagePermission,label:string,desc:string}[]=[{key:'property',label:'Property Map',desc:'View blocks, floors, rooms and beds.'},{key:'residents',label:'Residents',desc:'Resident lifecycle.'},{key:'vacancy',label:'Vacancy',desc:'Exact vacant bed search.'},{key:'payments',label:'Rent & Payments',desc:'Payments and receipts.'},{key:'food',label:'Food & Kitchen',desc:'Kitchen operations.'},{key:'staff',label:'Staff & Workers',desc:'Staff records.'},{key:'maintenance',label:'Maintenance',desc:'Issues and repairs.'},{key:'assets',label:'Assets & Inventory',desc:'Inventory.'},{key:'utilities',label:'Utilities',desc:'Utilities.'},{key:'expenses',label:'Expenses',desc:'Sensitive expense ledger.'},{key:'vendors',label:'Vendors & Purchases',desc:'Suppliers.'},{key:'calendar',label:'Calendar',desc:'Schedules.'},{key:'reports',label:'Reports',desc:'Reports and exports.'},{key:'documents',label:'Documents',desc:'Encrypted documents.'},{key:'notifications',label:'Notifications',desc:'Alerts.'},{key:'activity',label:'Activity Log',desc:'Audit trail.'}];
}
