import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { StoreService } from '../core/store.service';
@Component({standalone:true,imports:[FormsModule],template:`
<div class="page-head"><div><p class="eyebrow">LIVE BED AVAILABILITY</p><h1>Vacancies</h1><p>See exactly which sharing, block, floor, room and bed is available before check-in.</p></div><button class="primary-btn" (click)="assignResident()">+ Add Tenant</button></div>
<div class="stats-grid mini"><article class="stat-card"><div><strong>{{store.vacantBeds().length}}</strong><span>Total vacant beds</span><small>Live from room inventory</small></div></article>@for(s of sharingSummary();track s.sharing){<article class="stat-card"><div><strong>{{s.beds}}</strong><span>{{s.sharing}} Sharing</span><small>{{s.rooms}} rooms · {{rateLabel(s.sharing)}}</small></div></article>}</div>
<section class="panel vacancy-filter-panel active-filter-surface"><div class="panel-head"><div><p class="eyebrow">FIND A VACANCY</p><h2>Filter available beds</h2><p>Sharing options show only when at least one vacant bed exists.</p></div><button class="link-btn" (click)="clearFilters()">Clear filters</button></div><div class="filter-row"><span class="filter-tag">FILTERS</span><label>Sharing<select [(ngModel)]="sharing" (ngModelChange)="sharingChanged()"><option value="all">All available sharing</option>@for(x of sharingOptions();track x){<option [value]="x">{{x}} Sharing · {{sharingBedCount(x)}} beds vacant</option>}</select></label><label>Block<select [(ngModel)]="block" (ngModelChange)="filterChanged()"><option value="all">All Blocks</option>@for(b of availableBlocks();track b.id){<option [value]="b.id">{{b.name}}</option>}</select></label><label>Floor<select [(ngModel)]="floor" (ngModelChange)="filterChanged()"><option value="all">All Floors</option>@for(f of floorOptions();track f){<option [value]="f">{{floorName(f)}}</option>}</select></label><label>Preference<select [(ngModel)]="amenity"><option value="all">Any preference</option><option value="ac">AC</option><option value="bath">Attached Bath</option></select></label></div></section>
<div class="vacancy-layout"><aside class="vacancy-summary"><h3>Block & floor availability</h3>@for(g of grouped();track g.key){<button [class.active]="g.key===selectedGroup()" (click)="selectGroup(g.key)"><span><b>{{g.label}}</b><small>{{g.rooms}} rooms · {{g.sharings}}</small></span><strong>{{g.beds}}</strong></button>}</aside><section class="vacancy-results"><div class="panel-head"><div><p class="eyebrow">EXACT VACANCIES</p><h2>{{filtered().length}} rooms available</h2><p>{{store.vacantBeds().length}} total vacant beds across the PG.</p></div></div><div class="vacancy-cards">@for(v of filtered();track v.room.id){<article><div class="vacancy-card-head"><div><span class="block-pill">{{blockName(v.blockId)}}</span><h3>Room {{v.room.number}}</h3><p>{{floorName(v.floor)}} · {{v.room.sharing}} Sharing</p></div><div class="rate-stack"><span>Starting rate</span><strong>{{rateLabel(v.room.sharing)}}</strong></div></div><div class="amenities"><span>{{v.room.ac?'AC':'Non-AC'}}</span><span>{{v.room.attachedBath?'Attached Bath':'Common Bath'}}</span><span>{{vacantInRoom(v.room)}}/{{v.room.beds.length}} beds vacant</span></div><div class="bed-list">@for(b of v.room.beds;track b.id){<button [class.free]="b.status==='vacant'" [disabled]="b.status!=='vacant'" (click)="assignBed(b.id)">{{b.label}}<small>{{b.status==='vacant'?'Vacant · Assign':'Occupied'}}</small></button>}</div><button class="secondary-btn" (click)="assignFirstVacant(v.room.id)">Choose this room</button></article>}@empty{<div class="premium-empty"><h3>No vacancy for these filters</h3><p>Try another sharing, block or floor.</p></div>}</div></section></div>
`,styles:[`.vacancy-filter-panel{margin-bottom:14px}.rate-stack{text-align:right}.rate-stack span,.rate-stack strong{display:block}.rate-stack span{font-size:8px;color:#7b8799;text-transform:uppercase;letter-spacing:.08em}.rate-stack strong{font-size:14px;color:#332f6f}.vacancy-card-head{align-items:flex-start}.premium-empty{grid-column:1/-1}`]})
export class VacancyPage{
 block='all';floor='all';sharing='all';amenity='all';selectedGroup=signal('all');
 constructor(public store:StoreService,private router:Router){}
 blockName(id:string){return this.store.blocks().find(b=>b.id===id)?.name||`Block ${id}`;}
 vacantInRoom(r:any){return r.beds.filter((b:any)=>b.status==='vacant').length;}
 rateLabel(sharing:number){const n=this.store.sharingRate(sharing);return n>0?`₹${n.toLocaleString('en-IN')} / month`:'Rate not set';}
 sharingOptions(){return [...new Set<number>(this.store.vacantBeds().map(v=>Number(v.room.sharing)))].sort((a,b)=>a-b);}
 sharingBedCount(n:number){return this.store.vacantBeds().filter(v=>v.room.sharing===n).length;}
 sharingSummary(){return this.sharingOptions().map(sharing=>({sharing,beds:this.sharingBedCount(sharing),rooms:new Set(this.store.vacantBeds().filter(v=>v.room.sharing===sharing).map(v=>v.room.id)).size}));}
 availableBlocks(){const ids=new Set(this.store.vacantBeds().filter(v=>this.sharing==='all'||String(v.room.sharing)===this.sharing).map(v=>v.blockId));return this.store.blocks().filter(b=>ids.has(b.id));}
 floorOptions(){const rows=this.store.vacantBeds().filter(v=>(this.block==='all'||v.blockId===this.block)&&(this.sharing==='all'||String(v.room.sharing)===this.sharing));return [...new Set<number>(rows.map(v=>Number(v.floor)))].sort((a,b)=>a-b);}
 sharingChanged(){this.block='all';this.floor='all';this.selectedGroup.set('all');}
 filterChanged(){this.selectedGroup.set('all');if(this.floor!=='all'&&!this.floorOptions().includes(Number(this.floor)))this.floor='all';}
 clearFilters(){this.block='all';this.floor='all';this.sharing='all';this.amenity='all';this.selectedGroup.set('all');}
 selectGroup(key:string){this.selectedGroup.set(key);if(key==='all'){this.block='all';this.floor='all';return;}const i=key.lastIndexOf('-'),b=key.slice(0,i),f=key.slice(i+1);this.block=b;this.floor=f;}
 assignResident(){void this.router.navigate(['/residents'],{queryParams:{add:1}});} assignBed(bedId:string){void this.router.navigate(['/residents'],{queryParams:{add:1,bed:bedId}});} assignFirstVacant(roomId:string){const v=this.store.vacantBeds().find(x=>x.room.id===roomId);if(v)this.assignBed(v.bed.id);}
 filtered(){const unique=new Map<string,any>();for(const v of this.store.vacantBeds()){if(this.block!=='all'&&v.blockId!==this.block)continue;if(this.floor!=='all'&&String(v.floor)!==this.floor)continue;if(this.sharing!=='all'&&String(v.room.sharing)!==this.sharing)continue;if(this.amenity==='ac'&&!v.room.ac)continue;if(this.amenity==='bath'&&!v.room.attachedBath)continue;unique.set(v.room.id,v);}return [...unique.values()];}
 grouped(){const source=this.store.vacantBeds().filter(v=>this.sharing==='all'||String(v.room.sharing)===this.sharing);const rows=[{key:'all',label:'All Blocks & Floors',rooms:new Set(source.map(v=>v.room.id)).size,beds:source.length,sharings:this.sharing==='all'?'All sharing':`${this.sharing} Sharing`}];for(const b of this.store.blocks()){for(let f=0;f<b.floors;f++){const x=source.filter(v=>v.blockId===b.id&&v.floor===f);if(x.length){const sh=[...new Set<number>(x.map(v=>Number(v.room.sharing)))].sort((a,b)=>a-b).map(n=>`${n}S`).join(', ');rows.push({key:`${b.id}-${f}`,label:`${b.name} · ${this.floorName(f)}`,rooms:new Set(x.map(v=>v.room.id)).size,beds:x.length,sharings:sh});}}}return rows;}
 floorName(f:number){if(f===0)return'Ground Floor';const n=f%100;if(n>=11&&n<=13)return`${f}th Floor`;switch(f%10){case 1:return`${f}st Floor`;case 2:return`${f}nd Floor`;case 3:return`${f}rd Floor`;default:return`${f}th Floor`;}}
}
